services:
  frontend:
    build:
      target: dev
    volumes:
      - type: bind
        source: ./src/
        target: /etc/nginx/html/
    command:
      - nginx-debug
      - -g
      - daemon off;
