services:
  frontend:
    build:
      context: ./
    image: infinite_variety_exp-frontend
    working_dir: /frontend/
    restart: always
    ports:
      - 80:80
    # depends_on:
    #   backend:
    #     condition: service_healthy
  backend:
    build:
      context: ./backend/
    image: infinite_variety_exp-backend
    volumes:
      - type: bind
        source: ./backend/db/
        target: /backend/db/
    # volumes:
    #   - type: bind
    #     source: ./util/HealthCheck.java
    #     target: /HealthCheck.java
    #     read_only: true
    # restart: always
    # healthcheck:
    #   test: ["CMD", "java", "/HealthCheck.java", "||", "exit", "1"]
    #   start_period: 30s
